
author:     Brian G.
twitter:    brianmgonzalez
github:     briangonzalez

github_url: https://github.com/briangonzalez/jquery.pep.js

site:       jquery.pep.js
tagline:    kinetic drag for mobile & desktop

version:    0.1
ga:         'UX-XXXXXX'

google_fonts:
  - Source+Code+Pro